# only used in development
# this file will set up nginx as
# a reverse proxy to access frontend and backend
version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./digitalace-backend
    volumes:
      - ./digitalace-backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=api
      - DB_USER=postgres
      - DB_PASS=postgres_password
    depends_on:
      - db
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./digitalace-frontend
    volumes:
      - /app/node_modules
      - ./digitalace-frontend:/app
