# TODO: refactor all docker-compose files and dockerfiles
version: '3'
services:
  # only used for development:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./digitalace-frontend
    volumes:
      # - /app/node_modules
      - ./digitalace-frontend:/app
    ports:
      - '3000:3000'
  # only used for development, testing:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./digitalace-backend
    volumes:
      - ./digitalace-backend:/app
    ports:
      - '5000:5000'
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=digitalace_db
      - DB_USER=postgres
      - DB_PASS=postgres_password
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=digitalace_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
