# only used in development
version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./digitalace-backend
    volumes:
      - ./digitalace-backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=api
      - DB_USER=postgres
      - DB_PASS=postgres_password
    depends_on:
      - db
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./digitalace-frontend
    volumes:
      - /app/node_modules
      - ./digitalace-frontend:/app
