name: Run CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Build Docker Image
        run: docker build -t crownkira/digitalace-frontend-test -f ./digitalace-frontend/Dockerfile.test ./digitalace-frontend

      - name: Install Dependencies
        run: docker build -t crownkira/digitalace-frontend-test -f ./digitalace-frontend/Dockerfile.test ./digitalace-frontend

      - name: Run CI
        run: |
          docker run -e CI=true crownkira/digitalace-frontend-test yarn run test --passWithNoTests
          docker-compose run api sh -c "python manage.py wait_for_db && python manage.py test && flake8 --ignore=E501,F401,F403,F405,W503"
