name: Deployment From Github To AWS
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Build Docker Image
        run: docker build -t crownkira/digitalace-frontend-test -f ./digitalace-frontend/Dockerfile.test ./digitalace-frontend

      - name: Install Dependencies
        run: docker build -t crownkira/digitalace-frontend-test -f ./digitalace-frontend/Dockerfile.test ./digitalace-frontend

      - name: Run CI
        run: |
          docker run -e CI=true crownkira/digitalace-frontend-test yarn run test --passWithNoTests
          docker-compose run api sh -c "python manage.py wait_for_db && python manage.py test && flake8 --ignore=E501,F401,F403,F405,W503"

  deploy:
    needs: test
    name: Build and deploy DigitaLAce
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
        with:
          submodules: 'recursive'

      # TODO: use community action
      - name: Build Docker Images
        run: |
          docker build -t crownkira/digitalace-frontend ./digitalace-frontend
          docker build -t crownkira/digitalace-backend ./digitalace-backend
          docker build -t crownkira/digitalace-nginx ./nginx

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      - name: Push Docker Images to Docker Hub
        run: |
          docker push crownkira/digitalace-frontend
          docker push crownkira/digitalace-backend
          docker push crownkira/digitalace-nginx

      - name: Generate Deployment Package
        run: zip -r deploy.zip *

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: digitalace
          environment_name: Digitalace-env
          version_label: 'digitalace-${{ steps.format-time.outputs.replaced }}'
          region: us-east-2
          deployment_package: deploy.zip
